version: '2'

networks:
  net1.test:

services:
  db:
    build: db/
    ports:
        - 3306:3306
    hostname: db
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      net1.test:

#  kamailio: 
#    build: kamailio/
#    depends_on:
#      - db
#    volumes:
#      - ./kamailio/root:/root
#      - ./kamailio/config:/usr/local/etc/kamailio
#    hostname: kamailio

  pcscf:
    build: pcscf/
    depends_on:
      - db
    volumes:
      - ./pcscf/config:/usr/local/etc/kamailio
    hostname: pcscf
    domainname: net1.test
    ports:
      - "4060:4060/udp"
    networks:
      net1.test:
        aliases:
          - db.net1.test

  scscf:
    build: scscf/
    depends_on:
      - db
    volumes:
      - ./scscf/config:/usr/local/etc/kamailio
    hostname: scscf
    domainname: net1.test
    ports:
      - "6060:6060/udp"
      - "3870:3870"
    networks:
      net1.test:
        aliases:
          - scscf.net1.test

  icscf:
    build: icscf/
    depends_on:
      - db
    volumes:
      - ./icscf/config:/usr/local/etc/kamailio
    hostname: icscf
    domainname: net1.test
    ports:
      - "5060:5060/udp"
      - "3869:3869"
    networks:
      net1.test:
        aliases:
          - icscf.net1.test

  fhoss:
    build: fhoss/
    depends_on:
      - db
    volumes:
      - ./fhoss/root:/root
      - ./fhoss/config/DiameterPeerHSS.xml:/opt/OpenIMSCore/FHoSS/deploy/DiameterPeerHSS.xml
      - ./fhoss/config/hibernate.properties:/opt/OpenIMSCore/FHoSS/deploy/hibernate.properties
      - ./fhoss/config/hss.properties:/opt/OpenIMSCore/FHoSS/deploy/hss.properties
    ports:
      - "8080:8080"
      - "3868:3868"
    hostname: hss
    domainname: net1.test
    networks:
      net1.test:
        aliases:
          - hss.net1.test
    
    